void 	FakeMGL_exit(void);
void	FakeMGL_fatalError(const char *msg);
const char * FakeMGL_errorMsg(m_int err);
m_int 	FakeMGL_result(void);
m_int 	FakeMGL_registerDriver(const char *name,void *driver);
void	FakeMGL_unregisterAllDrivers(void);
void 	FakeMGL_detectGraph(m_int *driver,m_int *mode);
uchar *	FakeMGL_availableModes(void);
m_int	FakeMGL_modeResolution(m_int mode,m_int *xRes,m_int *yRes,m_int *bitsPerPixel);
bool	FakeMGL_init(m_int *driver,m_int *mode,const char *mglpath);
bool	FakeMGL_initWindowed(const char *mglpath);
void	FakeMGL_setSuspendAppCallback(MGL_suspend_cb_t staveState);
bool	FakeMGL_changeDisplayMode(m_int mode);
m_int	FakeMGL_availablePages(m_int mode);
MGLDC	* FakeMGL_createDisplayDC(m_int numBuffers);
m_int	FakeMGL_surfaceAccessType(MGLDC *dc);
MGLDC *	FakeMGL_makeCurrentDC(MGLDC *dc);
MGLDC 	* FakeMGL_createMemoryDC(m_int xSize,m_int ySize,m_int bitsPerPixel,pixel_format_t *pf);
m_int 	FakeMGL_sizex(MGLDC *dc);
m_int 	FakeMGL_sizey(MGLDC *dc);
void	FakeMGL_setActivePage(MGLDC *dc,m_int page);
void	FakeMGL_setVisualPage(MGLDC *dc,m_int page,m_int waitVRT);
void	FakeMGL_setAppInstance(MGL_HINSTANCE hInstApp);
const char * FakeMGL_modeDriverName(m_int mode);
bool	FakeMGL_destroyDC(MGLDC *dc);
void 	FakeMGL_registerFullScreenWindow(HWND hwndFullScreen);
MGLDC	* FakeMGL_createWindowedDC(MGL_HWND hwnd);
void 	ASMAPI MGL_beginDirectAccess(void);
void 	ASMAPI MGL_endDirectAccess(void);
void 	FakeMGL_setPalette(MGLDC *dc,palette_t *pal,m_int numColors,m_int startIndex);
void	FakeMGL_realizePalette(MGLDC *dc,m_int numColors,m_int startIndex,m_int waitVRT);
void 	FakeMGL_stretchBltCoord(MGLDC *dst,MGLDC *src,m_int left,m_int top,m_int right,m_int bottom,m_int dstLeft,m_int dstTop,m_int dstRight,m_int dstBottom);
void 	FakeMGL_bitBltCoord(MGLDC *dst,MGLDC *src,m_int left,m_int top,m_int right,m_int bottom,m_int dstLeft,m_int dstTop,m_int op);
bool	FakeMGL_setWinDC(MGLDC *dc,MGL_HDC hdc);
void	FakeMGL_appActivate(MGLDC *winDC,bool active);
bool	FakeMGL_activatePalette(MGLDC *dc,bool unrealize);


